extends Node

signal game_object_became_explane
signal game_object_became_idle

signal npc_became_talk
signal puzzle_mouse_clicked
signal object_mouse_clicked
signal dialogue_box_clicked

signal dialogue_completed
